### ISSUE TITLE
rsa file for multipass

### ISSUE THREAD

**Issue by pedro-sys** [AshAvalanche/ansible-avalanche-getting-started#37]
the id_rsa file in files/multipass/id_rsa have 644 permission mask instead of 600

**Comment by Nuttymoon** [comment]
Hi @pedro-sys, This is a known issue that comes from the fact that Git cannot version a file with `600` permissions. We are changing the mode in the `setup.sh` script:

https://github.com/AshAvalanche/ansible-avalanche-getting-started/blob/eae729cdcaa20382e8ab58849e11f294aefacfba/bin/setup.sh#L25

**Comment by Nuttymoon** [comment]
See https://github.com/AshAvalanche/ansible-avalanche-getting-started/pull/34#issuecomment-1647848093
